module.exports = {
    prefix: 'tw-',
    darkMode: 'media',
    theme: {
        extend: {
            spacing: {
                '3xs': '2px',
                '2xs': '4px',
                'xs': '6px',
                's': '8px',
                'st': '10px',
                'm': '12px',
                'l': '16px',
                'xl': '20px',
                '2xl': '24px',
                '3xl': '28px'
            }
        },
        width: {
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '3/4': '75%',
            full: '100%',
            screen: '100vw',
            auto: 'auto'
        },
        height: {
            full: '100%',
            screen: '100vh',
            auto: 'auto'
        },
        screens: {
            sm: {min: "640px"},
            md: {min: "768px"},
            lg: {min: "1024px"}
        }
    },
    variants: {
        extend: {},
        appearance: []
    },

    // Plugins from the list
    // https://tailwindcss.com/docs/configuration#core-plugins
    corePlugins: [
        'alignContent',
        'alignItems',
        'alignSelf',
        'clear',
        'container',
        'cursor',
        'display',
        'flex',
        'flexDirection',
        'flexGrow',
        'flexShrink',
        'flexWrap',
        'float',
        'gridAutoColumns',
        'gridAutoFlow',
        'gridAutoRows',
        'gridColumn',
        'gridColumnEnd',
        'gridColumnStart',
        'gridRow',
        'gridRowEnd',
        'gridRowStart',
        'gridTemplateColumns',
        'gridTemplateRows',
        'height',
        'justifyContent',
        'justifyItems',
        'justifySelf',
        'order',
        'overflow',
        'overscrollBehavior',
        'placeItems',
        'placeSelf',
        'position',
        'textOverflow',
        'visibility',
        'width',
        'wordBreak',
        'zIndex',
        'minWidth',
        'minHeight',
        'margin',
        'padding',
        'inset'
    ],

    // TODO: remove after fixing usage of tailwind classes in ts{x}, wml and tmpl files.
    // https://tailwindcss.com/docs/content-configuration#class-detection-in-depth
    safelist: [
        'tw-cursor-auto',
        'tw-cursor-default',
        'tw-cursor-pointer',
        'tw-cursor-wait',
        'tw-cursor-text',
        'tw-cursor-move',
        'tw-cursor-not-allowed',
        'tw-justify-start',
        'tw-justify-end',
        'tw-justify-center',
        'tw-justify-between',
        'tw-justify-around',
        'tw-justify-evenly',
        'tw-justify-items-auto',
        'tw-justify-items-start',
        'tw-justify-items-end',
        'tw-justify-items-center',
        'tw-justify-items-stretch',
        'tw-justify-self-auto',
        'tw-justify-self-start',
        'tw-justify-self-end',
        'tw-justify-self-center',
        'tw-justify-self-stretch',
        'tw-items-start',
        'tw-items-end',
        'tw-items-center',
        'tw-items-baseline',
        'tw-items-stretch',
        'tw-flex-1',
        'tw-flex-auto',
        'tw-flex-initial',
        'tw-flex-none',
        'tw-flex-row',
        'tw-flex-row-reverse',
        'tw-flex-col',
        'tw-flex-col-reverse',
        'tw-flex-grow-0',
        'tw-flex-grow',
        'tw-flex-shrink-0',
        'tw-flex-shrink',
        'tw-flex-wrap',
        'tw-flex-wrap-reverse',
        'tw-flex-no-wrap',
        'tw-grid',
        'tw-grid-flow-row',
        'tw-grid-flow-col',
        'tw-grid-flow-row-dense',
        'tw-grid-flow-col-dense',
        'tw-grid-cols-1',
        'tw-grid-cols-2',
        'tw-grid-cols-3',
        'tw-grid-cols-4',
        'tw-grid-cols-5',
        'tw-grid-cols-6',
        'tw-grid-cols-7',
        'tw-grid-cols-8',
        'tw-grid-cols-9',
        'tw-grid-cols-10',
        'tw-grid-cols-11',
        'tw-grid-cols-12',
        'tw-grid-cols-none',
        'tw-grid-rows-1',
        'tw-grid-rows-2',
        'tw-grid-rows-3',
        'tw-grid-rows-4',
        'tw-grid-rows-5',
        'tw-grid-rows-6',
        'tw-grid-rows-none'
    ]
}
